version: '3'

services: 
    web:
        build: /backend/.
        command: python CurrencyExchange/manage.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000
    # scrapping:
    #     build: .
    #     command: python download/main.py